apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-local-monitors
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/IliePM/mlops-infra'
    targetRevision: HEAD
    path: prometheus
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mlops-prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true